language: python

python:
  - 3.5
  - 3.6

services:
  - postgresql

install:
  - pip install -r requirements-dev.txt

before_script:
  - psql -c 'create database travis_ci_db;' -U postgres
  - ./manage.py migrate api
  - ./manage.py migrate

script:
  - ./ci.sh

after_success:
  - codecov
